STARTING_CASH = 8000
TRACK_COST_PER_UNIT = 1
TRAIN_COSTS = {
    "EMD_E9": 700,
}
MAINTENANCE_COST = 250
PASSENGER_FARE = 7.38
MAINTENANCE_VISIT_MIN = 10
MAINTENANCE_VISIT_MAX = 15
MAINTENANCE_DURATION_SECONDS = 3.0
